language: r
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
    - stage: "R CMD check"
      name: "Old Release"
      r: oldrel


    - name: "Release"
      r: release


    - name: "Devel"
      r: devel


    - stage: "Deploy"
      name: "pkgdown"
      r: release
      if: |
        branch IN (master, travis, rc-v1.0.0) AND \
        type = push AND \
        repo = rstudio/reactlog
      before_deploy: # build site and copy over files
        - Rscript -e 'if(!require("pkgdown")) install.packages("pkgdown")'
        - Rscript -e 'pkgdown::build_site()'
        # copy reandme images to be hosted by github
        - Rscript -e 'stopifnot(file.copy("readme-images/", "docs/", recursive = TRUE))'
        # copy inst/reactlog/ to docs/demo/ to maintain live demo on github
        - Rscript -e 'stopifnot(file.copy("inst/reactlog/", "docs/", recursive = TRUE)); stopifnot(file.rename("docs/reactlog/", "docs/demo/"))'
      deploy:
        provider: pages # github pages
        local-dir: docs # deploy from docs folder
        skip-cleanup: true # keep pkgdown output
        keep-history: false # overwrite all git history
        on:
          # deploy on any branch as condition is done above
          all_branches: true
        github-token:
          secure:
            "fH2wg82kkxo6hWJIejIuihnwjysnxMkE6IgmSe6v5Jhg4jNhTZOAZXt0c6nk+nOZfgRKk5xiXbF1WlQWr0lrJakJZ8uKPVJCyZNQMu0A2KykxFoQDK/nZoTzgHTfsTHNpPvE3aaWCPS/VDo1mYFV1vv2MvxpPgcYKFClGeh74oJX30yVE868/HUYVeGnOjRghG7ZMQo7W02dm9W8KSBR1sTAoU0r84ehWCWG0xQCUOAQfoKv5anzx437FFLAxG2ACaBRM9k9I+FFZu6yIlNGC0Qbnsb68uWqtHleofh1FKqGG8CwSgEMQfGrVfqYK0pYVkHueICpIlN0OwFIj+PuL2TTKDPI3XMCkV9m0wp/a3Snd+YjlntlkQ2tdL2l8OhMw9ZE0Q0QXzAWKix+dJ8+GZmtlVhBKG+grZlxiVoTmxTPl13NoQMGIUKkAKuim1nAMJ1CnwXrjb9uk7IUE7ua2E0dDuUJmjtONUwrGAjnq7uSvMn2QbCEml06NuoI+L0NBlaXCgd0MDJoROsqSFlptYPsarkcQWrXZx488OjStmgIWZUmgZqqeWseo+/b9t6MWQk8FTEEvWvrzchaUf3FJbtQZStA64OTMtDJFrivY/mMRLIVKbfVViDJ3SgHA8b1ppZG+CGp7+DLeXlkShtVdjGwnMwYlwivubdCz1nTG7A="
