language: r
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
    - stage: test
      r: oldrel

    - stage: test
      r: release

    - stage: test
      r: devel
      warnings_are_errors: false

    - stage: deploy
      r: devel
      if: branch IN (master, travis)
      r_binary_packages:
        - pkgdown
      after_success:
        - Rscript -e 'pkgdown::build_site()'
        # copy inst/reactlog/ to docs/demo/ to maintain live demo
        - Rscript -e 'stopifnot(file.copy("inst/reactlog/", "docs/", recursive = TRUE))'
        - Rscript -e 'stopifnot(file.rename("docs/reactlog/", "docs/demo/"))'
      deploy:
        provider: pages
        skip-cleanup: true
        github-token:
          secure:
            "fH2wg82kkxo6hWJIejIuihnwjysnxMkE6IgmSe6v5Jhg4jNhTZOAZXt0c6nk+nOZfgRKk5xiXbF1WlQWr0lrJakJZ8uKPVJCyZNQMu0A2KykxFoQDK/nZoTzgHTfsTHNpPvE3aaWCPS/VDo1mYFV1vv2MvxpPgcYKFClGeh74oJX30yVE868/HUYVeGnOjRghG7ZMQo7W02dm9W8KSBR1sTAoU0r84ehWCWG0xQCUOAQfoKv5anzx437FFLAxG2ACaBRM9k9I+FFZu6yIlNGC0Qbnsb68uWqtHleofh1FKqGG8CwSgEMQfGrVfqYK0pYVkHueICpIlN0OwFIj+PuL2TTKDPI3XMCkV9m0wp/a3Snd+YjlntlkQ2tdL2l8OhMw9ZE0Q0QXzAWKix+dJ8+GZmtlVhBKG+grZlxiVoTmxTPl13NoQMGIUKkAKuim1nAMJ1CnwXrjb9uk7IUE7ua2E0dDuUJmjtONUwrGAjnq7uSvMn2QbCEml06NuoI+L0NBlaXCgd0MDJoROsqSFlptYPsarkcQWrXZx488OjStmgIWZUmgZqqeWseo+/b9t6MWQk8FTEEvWvrzchaUf3FJbtQZStA64OTMtDJFrivY/mMRLIVKbfVViDJ3SgHA8b1ppZG+CGp7+DLeXlkShtVdjGwnMwYlwivubdCz1nTG7A="
        keep-history: false
        local-dir: docs
