language: r
sudo: false
cache: packages


matrix:
  include:
    - r: oldrel

    - r: release

    - r: devel
      warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
