name: 'Copy files to pkgdown folder'
description: 'Copy all files necessary for the pkgdown website to work'
author: 'Barret Schloerke'
runs:
  using: "composite"
  steps:
    - name: Copy github.io hosted files
      shell: Rscript {0}
      run: |
        # copy readme files
        stopifnot(
          file.copy("readme-images/", "pkgdown/", recursive = TRUE)
        )
        # copy demo files
        stopifnot(
          file.copy("inst/reactlog/", "pkgdown/", recursive = TRUE)
        )
        # rename to 'demo'
        stopifnot(
          file.rename("pkgdown/reactlog", "pkgdown/demo")
        )
